/// Til tizimi - uz, ru, en
class S {
  static String _lang = 'uz';
  static String get lang => _lang;
  static void setLang(String l) => _lang = l;

  static String get(String key) => (_all[key]?[_lang]) ?? (_all[key]?['uz']) ?? key;

  /// Inline 3-language helper for content strings (task templates,
  /// achievements, daily challenges, etc.) that don't fit the keyed map.
  static String tr(String uz, String ru, String en) {
    if (_lang == 'ru') return ru;
    if (_lang == 'en') return en;
    return uz;
  }

  static const _all = <String, Map<String, String>>{
    // ── Common ──
    'app_name':      {'uz': 'MotivAI', 'ru': 'MotivAI', 'en': 'MotivAI'},
    'loading':       {'uz': 'Yuklanmoqda...', 'ru': 'Загрузка...', 'en': 'Loading...'},
    'save':          {'uz': 'Saqlash', 'ru': 'Сохранить', 'en': 'Save'},
    'cancel':        {'uz': 'Bekor', 'ru': 'Отмена', 'en': 'Cancel'},
    'delete':        {'uz': 'O\'chirish', 'ru': 'Удалить', 'en': 'Delete'},
    'error':         {'uz': 'Xato yuz berdi', 'ru': 'Произошла ошибка', 'en': 'An error occurred'},
    'retry':         {'uz': 'Qayta urinish', 'ru': 'Повторить', 'en': 'Retry'},
    'yes':           {'uz': 'Ha', 'ru': 'Да', 'en': 'Yes'},
    'no':            {'uz': 'Yo\'q', 'ru': 'Нет', 'en': 'No'},
    'done':          {'uz': 'Tayyor', 'ru': 'Готово', 'en': 'Done'},
    'continue_btn':  {'uz': 'Davom etish', 'ru': 'Продолжить', 'en': 'Continue'},

    // ── Auth ──
    'login':         {'uz': 'Kirish', 'ru': 'Войти', 'en': 'Login'},
    'register':      {'uz': 'Ro\'yxatdan o\'tish', 'ru': 'Регистрация', 'en': 'Register'},
    'email':         {'uz': 'Email', 'ru': 'Эл. почта', 'en': 'Email'},
    'password':      {'uz': 'Parol', 'ru': 'Пароль', 'en': 'Password'},
    'full_name':     {'uz': 'To\'liq ism', 'ru': 'Полное имя', 'en': 'Full name'},
    'username':      {'uz': 'Foydalanuvchi nomi', 'ru': 'Имя пользователя', 'en': 'Username'},
    'forgot_pass':   {'uz': 'Parolni unutdingizmi?', 'ru': 'Забыли пароль?', 'en': 'Forgot password?'},
    'no_account':    {'uz': 'Hisobingiz yo\'qmi?', 'ru': 'Нет аккаунта?', 'en': 'No account?'},
    'has_account':   {'uz': 'Hisobingiz bormi?', 'ru': 'Есть аккаунт?', 'en': 'Have an account?'},
    'login_google':  {'uz': 'Google bilan kirish', 'ru': 'Войти через Google', 'en': 'Sign in with Google'},
    'login_phone':   {'uz': 'Telefon bilan kirish', 'ru': 'Войти по телефону', 'en': 'Sign in with Phone'},
    'or':            {'uz': 'yoki', 'ru': 'или', 'en': 'or'},
    'motto':         {'uz': 'Maqsadga — har kuni bir qadam!', 'ru': 'К цели — каждый день по шагу!', 'en': 'One step closer to your goal every day!'},
    'min_6':         {'uz': 'Kamida 6 belgi', 'ru': 'Минимум 6 символов', 'en': 'At least 6 characters'},
    'enter_email':   {'uz': 'Email kiriting', 'ru': 'Введите email', 'en': 'Enter email'},
    'valid_email':   {'uz': 'To\'g\'ri email kiriting', 'ru': 'Введите корректный email', 'en': 'Enter valid email'},
    'reset_pass':    {'uz': 'Parolni tiklash', 'ru': 'Восстановить пароль', 'en': 'Reset password'},
    'reset_sent':    {'uz': 'Parol tiklash havolasi yuborildi', 'ru': 'Ссылка отправлена', 'en': 'Reset link sent'},
    'phone_number':  {'uz': 'Telefon raqam', 'ru': 'Номер телефона', 'en': 'Phone number'},
    'send_sms':      {'uz': 'SMS yuborish', 'ru': 'Отправить SMS', 'en': 'Send SMS'},
    'coming_soon':   {'uz': 'Tez orada qo\'shiladi', 'ru': 'Скоро будет доступно', 'en': 'Coming soon'},

    // ── Navigation ──
    'home':          {'uz': 'Bosh sahifa', 'ru': 'Главная', 'en': 'Home'},
    'chat':          {'uz': 'AI Chat', 'ru': 'AI Чат', 'en': 'AI Chat'},
    'rating':        {'uz': 'Reyting', 'ru': 'Рейтинг', 'en': 'Rating'},
    'analytics':     {'uz': 'Tahlil', 'ru': 'Аналитика', 'en': 'Analytics'},
    'profile':       {'uz': 'Profil', 'ru': 'Профиль', 'en': 'Profile'},

    // ── Dashboard ──
    'good_morning':  {'uz': 'Xayrli tong', 'ru': 'Доброе утро', 'en': 'Good morning'},
    'good_day':      {'uz': 'Xayrli kun', 'ru': 'Добрый день', 'en': 'Good afternoon'},
    'good_evening':  {'uz': 'Xayrli kech', 'ru': 'Добрый вечер', 'en': 'Good evening'},
    'today_goal':    {'uz': 'Bugungi maqsad', 'ru': 'Цель дня', 'en': 'Today\'s goal'},
    'today_tasks':   {'uz': 'Bugungi vazifalar', 'ru': 'Задачи на сегодня', 'en': 'Today\'s tasks'},
    'no_tasks':      {'uz': 'Hozircha vazifalar yo\'q', 'ru': 'Пока нет задач', 'en': 'No tasks yet'},
    'add_task':      {'uz': 'Vazifa qo\'shish', 'ru': 'Добавить задачу', 'en': 'Add task'},
    'all_done':      {'uz': 'Barcha vazifalar bajarildi!', 'ru': 'Все задачи выполнены!', 'en': 'All tasks completed!'},
    'completed':     {'uz': 'bajarildi', 'ru': 'выполнено', 'en': 'completed'},
    'level':         {'uz': 'Daraja', 'ru': 'Уровень', 'en': 'Level'},
    'points':        {'uz': 'ball', 'ru': 'баллов', 'en': 'points'},
    'streak':        {'uz': 'Streak', 'ru': 'Серия', 'en': 'Streak'},
    'day':           {'uz': 'kun', 'ru': 'дн.', 'en': 'days'},
    'tasks_label':   {'uz': 'Vazifalar', 'ru': 'Задачи', 'en': 'Tasks'},
    'ai_suggest':    {'uz': 'AI Tavsiyalar', 'ru': 'AI Рекомендации', 'en': 'AI Suggestions'},
    'pull_refresh':  {'uz': 'Yangilash uchun pastga torting', 'ru': 'Потяните вниз для обновления', 'en': 'Pull to refresh'},
    'today':         {'uz': 'bugun', 'ru': 'сегодня', 'en': 'today'},

    // ── Task ──
    'easy':          {'uz': 'Oson', 'ru': 'Легко', 'en': 'Easy'},
    'medium':        {'uz': 'O\'rta', 'ru': 'Средне', 'en': 'Medium'},
    'hard':          {'uz': 'Qiyin', 'ru': 'Сложно', 'en': 'Hard'},
    'expert':        {'uz': 'Expert', 'ru': 'Эксперт', 'en': 'Expert'},
    'task_title':    {'uz': 'Vazifa nomi', 'ru': 'Название задачи', 'en': 'Task title'},
    'task_desc':     {'uz': 'Tavsif', 'ru': 'Описание', 'en': 'Description'},
    'duration':      {'uz': 'Davomiyligi (daqiqa)', 'ru': 'Продолжительность (мин)', 'en': 'Duration (min)'},
    'priority':      {'uz': 'Muhimlik', 'ru': 'Приоритет', 'en': 'Priority'},
    'low':           {'uz': 'Past', 'ru': 'Низкий', 'en': 'Low'},
    'high':          {'uz': 'Yuqori', 'ru': 'Высокий', 'en': 'High'},
    'urgent':        {'uz': 'Shoshilinch', 'ru': 'Срочный', 'en': 'Urgent'},
    'category':      {'uz': 'Kategoriya', 'ru': 'Категория', 'en': 'Category'},
    'task_added':    {'uz': 'Vazifa qo\'shildi!', 'ru': 'Задача добавлена!', 'en': 'Task added!'},

    // ── Chat ──
    'ai_assistant':  {'uz': 'AI Assistent', 'ru': 'AI Ассистент', 'en': 'AI Assistant'},
    'type_message':  {'uz': 'Xabar yozing...', 'ru': 'Введите сообщение...', 'en': 'Type a message...'},
    'ai_typing':     {'uz': 'AI yozmoqda...', 'ru': 'AI печатает...', 'en': 'AI is typing...'},
    'clear_chat':    {'uz': 'Tarixni tozalash', 'ru': 'Очистить историю', 'en': 'Clear history'},
    'chat_cleared':  {'uz': 'Suhbat tozalandi', 'ru': 'Чат очищен', 'en': 'Chat cleared'},

    // ── Leaderboard ──
    'all_time':      {'uz': 'Barcha vaqt', 'ru': 'За всё время', 'en': 'All time'},
    'this_week':     {'uz': 'Bu hafta', 'ru': 'Эта неделя', 'en': 'This week'},
    'students':      {'uz': 'talaba', 'ru': 'студ.', 'en': 'students'},
    'empty_board':   {'uz': 'Reyting hali bo\'sh', 'ru': 'Рейтинг пока пуст', 'en': 'Leaderboard is empty'},

    // ── Profile ──
    'settings':      {'uz': 'Sozlamalar', 'ru': 'Настройки', 'en': 'Settings'},
    'dark_mode':     {'uz': 'Tungi rejim', 'ru': 'Тёмная тема', 'en': 'Dark mode'},
    'light_mode':    {'uz': 'Kunduzgi rejim', 'ru': 'Светлая тема', 'en': 'Light mode'},
    'change_pass':   {'uz': 'Parolni o\'zgartirish', 'ru': 'Изменить пароль', 'en': 'Change password'},
    'language':      {'uz': 'Til', 'ru': 'Язык', 'en': 'Language'},
    'notifications': {'uz': 'Bildirishnomalar', 'ru': 'Уведомления', 'en': 'Notifications'},
    'clear_cache':   {'uz': 'Keshni tozalash', 'ru': 'Очистить кэш', 'en': 'Clear cache'},
    'logout':        {'uz': 'Chiqish', 'ru': 'Выйти', 'en': 'Log out'},
    'logout_confirm':{'uz': 'Hisobdan chiqmoqchimisiz?', 'ru': 'Вы хотите выйти?', 'en': 'Do you want to log out?'},
    'account':       {'uz': 'Hisob', 'ru': 'Аккаунт', 'en': 'Account'},
    'edit_profile':  {'uz': 'Profilni tahrirlash', 'ru': 'Редактировать профиль', 'en': 'Edit profile'},
    'achievements':  {'uz': 'Yutuqlar', 'ru': 'Достижения', 'en': 'Achievements'},
    'current_pass':  {'uz': 'Joriy parol', 'ru': 'Текущий пароль', 'en': 'Current password'},
    'new_pass':      {'uz': 'Yangi parol', 'ru': 'Новый пароль', 'en': 'New password'},
    'confirm_pass':  {'uz': 'Parolni tasdiqlang', 'ru': 'Подтвердите пароль', 'en': 'Confirm password'},
    'pass_changed':  {'uz': 'Parol o\'zgartirildi', 'ru': 'Пароль изменён', 'en': 'Password changed'},
    'pass_mismatch': {'uz': 'Parollar mos kelmadi', 'ru': 'Пароли не совпадают', 'en': 'Passwords don\'t match'},
    'select_lang':   {'uz': 'Tilni tanlang', 'ru': 'Выберите язык', 'en': 'Select language'},

    // ── Progress ──
    'weekly_points': {'uz': 'Haftalik ballar', 'ru': 'Баллы за неделю', 'en': 'Weekly points'},
    'total_points':  {'uz': 'Jami ball', 'ru': 'Всего баллов', 'en': 'Total points'},
    'cat_breakdown': {'uz': 'Kategoriya taqsimoti', 'ru': 'Разбивка по категориям', 'en': 'Category breakdown'},
    'next_level':    {'uz': 'Keyingi darajaga', 'ru': 'До следующего уровня', 'en': 'To next level'},

    // ── Completion ──
    'task_done':     {'uz': 'Bajarildi!', 'ru': 'Выполнено!', 'en': 'Completed!'},
    'level_up':      {'uz': 'DARAJA OSHDI!', 'ru': 'УРОВЕНЬ ПОВЫШЕН!', 'en': 'LEVEL UP!'},

    // ── Back to exit ──
    'back_exit':     {'uz': 'Chiqish uchun yana bir marta bosing', 'ru': 'Нажмите ещё раз для выхода', 'en': 'Press again to exit'},

    // ── Profile sections / tiles ──
    'auto_theme':       {'uz': 'Avto tema', 'ru': 'Авто тема', 'en': 'Auto theme'},
    'auto_theme_sub':   {'uz': 'Soatga qarab avtomatik', 'ru': 'По времени суток', 'en': 'Switch by clock'},
    'theme_color':      {'uz': 'Rang mavzusi', 'ru': 'Цветовая тема', 'en': 'Color theme'},
    'flashcards':       {'uz': 'Flashcards', 'ru': 'Карточки', 'en': 'Flashcards'},
    'habits':           {'uz': 'Kundalik odatlar', 'ru': 'Привычки', 'en': 'Habits'},
    'habits_sub':       {'uz': 'Kundalik rivojlanish', 'ru': 'Ежедневный рост', 'en': 'Daily growth'},
    'wrapped':          {'uz': 'Haftalik xulosa', 'ru': 'Итоги недели', 'en': 'Weekly wrap-up'},
    'smart_plan':       {'uz': 'Aqlli reja', 'ru': 'Умный план', 'en': 'Smart plan'},
    'smart_plan_sub':   {'uz': 'Vaqtni rejaga ajratish', 'ru': 'Распределение времени', 'en': 'Time-block planner'},
    'journey':          {'uz': 'Sayohat', 'ru': 'Путешествие', 'en': 'Journey'},
    'journey_sub':      {'uz': '30 kunlik progress', 'ru': '30-дневный прогресс', 'en': '30-day progress'},
    'heatmap':          {'uz': 'Mahsuldorlik xaritasi', 'ru': 'Карта продуктивности', 'en': 'Productivity heatmap'},
    'heatmap_sub':      {'uz': 'Soat va kun statistikasi', 'ru': 'Часы и дни', 'en': 'Hours and days'},
    'rituals':          {'uz': 'Rituallar', 'ru': 'Ритуалы', 'en': 'Rituals'},
    'rituals_sub':      {'uz': 'Takroriy eslatma', 'ru': 'Регулярные напоминания', 'en': 'Recurring reminders'},
    'friends':          {'uz': 'Do\'stlar', 'ru': 'Друзья', 'en': 'Friends'},
    'friends_sub':      {'uz': 'Taklif kodi orqali', 'ru': 'По коду приглашения', 'en': 'Via invite code'},
    'challenges':       {'uz': 'Chellenjlar', 'ru': 'Челленджи', 'en': 'Challenges'},
    'challenges_sub':   {'uz': '7 kunlik turnir', 'ru': '7-дневный турнир', 'en': '7-day tournament'},
    'sound_pack':       {'uz': 'Tovush pachkasi', 'ru': 'Звуковой пакет', 'en': 'Sound pack'},
    'haptics':          {'uz': 'Titrash kuchi', 'ru': 'Сила вибрации', 'en': 'Haptic strength'},
    'test_notif':       {'uz': 'Bildirishnomani sinash', 'ru': 'Тест уведомления', 'en': 'Test notification'},
    'test_notif_sub':   {'uz': '5 soniyadan keyin test keladi', 'ru': 'Через 5 секунд', 'en': 'Arrives in 5s'},
    'export_data':      {'uz': 'Ma\'lumotlarni eksport', 'ru': 'Экспорт данных', 'en': 'Export data'},
    'export_data_sub':  {'uz': 'JSON formatida', 'ru': 'В формате JSON', 'en': 'JSON format'},
    'share_template':   {'uz': 'Template ulashish', 'ru': 'Поделиться шаблоном', 'en': 'Share template'},
    'share_template_sub':{'uz':'Do\'stga jo\'natish uchun','ru':'Отправить другу','en':'Send to a friend'},
    'import_template':  {'uz': 'Template import', 'ru': 'Импорт шаблона', 'en': 'Import template'},
    'import_template_sub':{'uz':'JSON yopishtiring','ru':'Вставьте JSON','en':'Paste JSON'},
    'about_app':        {'uz': 'Ilova haqida', 'ru': 'О приложении', 'en': 'About app'},
    'about_motivai':    {'uz': 'MotivAI haqida', 'ru': 'О MotivAI', 'en': 'About MotivAI'},
    'help':             {'uz': 'Yordam', 'ru': 'Помощь', 'en': 'Help'},
    'help_sub':         {'uz': 'Qo\'llanma', 'ru': 'Руководство', 'en': 'Guide'},
    'privacy_policy':   {'uz': 'Maxfiylik siyosati', 'ru': 'Политика конфиденциальности', 'en': 'Privacy policy'},
    'terms_of_service': {'uz': 'Foydalanish shartlari', 'ru': 'Условия использования', 'en': 'Terms of service'},
    'delete_account':   {'uz': 'Akkauntni o\'chirish', 'ru': 'Удалить аккаунт', 'en': 'Delete account'},
    'delete_account_sub':{'uz':'Butunlay o\'chirish','ru':'Удалить полностью','en':'Permanent removal'},
    'reminder_min_one': {'uz': 'min oldin eslatma', 'ru': 'мин. до напоминания', 'en': 'min before reminder'},
    'reminder_off':     {'uz': 'O\'chirilgan', 'ru': 'Выключено', 'en': 'Off'},
    // ── Added by apply_i18n.py ──
    'app_motto_short': {'uz': 'Maqsadga - har kuni bir qadam', 'ru': 'К цели - каждый день по шагу', 'en': 'One step closer every day'},
    'app_about_full': {'uz': 'AI orqali talabalarga motivatsiya beruvchi ilova', 'ru': 'Приложение для мотивации студентов через AI', 'en': 'AI-powered motivation app for students'},
    'version_label': {'uz': 'MotivAI v2.2.0', 'ru': 'MotivAI v2.2.0', 'en': 'MotivAI v2.2.0'},
    'ai_mentor': {'uz': 'AI mentor', 'ru': 'AI ментор', 'en': 'AI mentor'},
    'ai_help': {'uz': 'AI yordam', 'ru': 'AI помощь', 'en': 'AI help'},
    'select_all': {'uz': 'Barchasini tanlash', 'ru': 'Выбрать всё', 'en': 'Select all'},
    'clear_all': {'uz': 'Hammasini tozalash', 'ru': 'Очистить всё', 'en': 'Clear all'},
    'mark_all_read': {'uz': 'Barchasini o\'qilgan qilish', 'ru': 'Отметить всё прочитанным', 'en': 'Mark all as read'},
    'skip': {'uz': 'O\'tkazib yuborish', 'ru': 'Пропустить', 'en': 'Skip'},
    'skipped': {'uz': 'O\'tkazib yuborildi', 'ru': 'Пропущено', 'en': 'Skipped'},
    'stop': {'uz': 'To\'xtatish', 'ru': 'Остановить', 'en': 'Stop'},
    'import_btn': {'uz': 'Import qilish', 'ru': 'Импортировать', 'en': 'Import'},
    'create_new': {'uz': 'Yangisini yaratish', 'ru': 'Создать новое', 'en': 'Create new'},
    'add_btn': {'uz': 'Qo\'shish', 'ru': 'Добавить', 'en': 'Add'},
    'remove_btn': {'uz': 'O\'chirish', 'ru': 'Удалить', 'en': 'Remove'},
    'copy': {'uz': 'Nusxa olish', 'ru': 'Копировать', 'en': 'Copy'},
    'copied': {'uz': 'Nusxa olindi', 'ru': 'Скопировано', 'en': 'Copied'},
    'nothing_found': {'uz': 'Hech narsa topilmadi', 'ru': 'Ничего не найдено', 'en': 'Nothing found'},
    'could_not_open': {'uz': 'Sahifa ochib bo\'lmadi', 'ru': 'Не удалось открыть страницу', 'en': 'Could not open page'},
    'yes_let_us_start': {'uz': 'Yaxshi, boshlayman', 'ru': 'Хорошо, начнём', 'en': 'OK, let\'s start'},
    'welcome': {'uz': 'Xush kelibsiz', 'ru': 'Добро пожаловать', 'en': 'Welcome'},
    'welcome_to_motivai': {'uz': 'MotivAI ga xush kelibsiz!', 'ru': 'Добро пожаловать в MotivAI!', 'en': 'Welcome to MotivAI!'},
    'color_theme_title': {'uz': 'Rang mavzusi', 'ru': 'Цветовая тема', 'en': 'Color theme'},
    'color_theme_pick': {'uz': 'Ilovaning rang palitrasini tanlang', 'ru': 'Выберите цветовую палитру', 'en': 'Pick the app\'s color palette'},
    'haptic_title': {'uz': 'Titrash kuchi', 'ru': 'Сила вибрации', 'en': 'Haptic strength'},
    'sound_pack_title': {'uz': 'Tovush pachkasi', 'ru': 'Звуковой пакет', 'en': 'Sound pack'},
    'auto_theme_hint': {'uz': 'Kechqurun dark, kunduzi light - avtomatik', 'ru': 'Вечером - тёмная, днём - светлая', 'en': 'Dark at night, light by day - auto'},
    'delete_account_warn': {'uz': 'Bu amal qaytarib bo\'lmaydi. Hamma vazifalar, XP, ', 'ru': 'Это действие нельзя отменить. Все задачи, XP, ', 'en': 'This action cannot be undone. All tasks, XP, '},
    'with_all_data': {'uz': 'Hamma ma\'lumotlar bilan birga', 'ru': 'Со всеми данными', 'en': 'Along with all data'},
    'delete_account_btn': {'uz': 'Akkauntni o\'chirish', 'ru': 'Удалить аккаунт', 'en': 'Delete account'},
    'test_notif_when': {'uz': '5 soniyadan keyin keladi', 'ru': 'Придёт через 5 секунд', 'en': 'Arrives in 5s'},
    'guide_help': {'uz': 'Qo\'llanma', 'ru': 'Руководство', 'en': 'Guide'},
    'guide_help_full': {'uz': 'Qo\'llanma va savollar', 'ru': 'Руководство и вопросы', 'en': 'Guide and FAQ'},
    'habits_title': {'uz': 'Kundalik odatlar', 'ru': 'Ежедневные привычки', 'en': 'Daily habits'},
    'habits_empty_title': {'uz': 'Hali odat yo\'q', 'ru': 'Привычек пока нет', 'en': 'No habits yet'},
    'habits_empty_sub': {'uz': 'Kundalik odat qo\'shing - streak orttiring', 'ru': 'Добавьте привычку - растите streak', 'en': 'Add a daily habit - grow your streak'},
    'habit_new': {'uz': 'Yangi odat', 'ru': 'Новая привычка', 'en': 'New habit'},
    'habit_name_label': {'uz': 'Odat nomi', 'ru': 'Название привычки', 'en': 'Habit name'},
    'habit_name_validate': {'uz': 'Ism va kamida 1 kunni tanlang', 'ru': 'Имя и хотя бы 1 день', 'en': 'Pick a name and at least 1 day'},
    'habit_delete_q': {'uz': 'Odatni o\'chirish?', 'ru': 'Удалить привычку?', 'en': 'Delete habit?'},
    'cancel_btn': {'uz': 'Bekor qilish', 'ru': 'Отмена', 'en': 'Cancel'},
    'friends_title': {'uz': 'Do\'stlar', 'ru': 'Друзья', 'en': 'Friends'},
    'friends_empty': {'uz': 'Hali do\'stlar yo\'q', 'ru': 'Друзей пока нет', 'en': 'No friends yet'},
    'friends_empty_sub': {'uz': 'Yuqoridagi "+" tugmasi orqali do\'st qo\'shing', 'ru': 'Добавьте друга через кнопку "+" сверху', 'en': 'Add a friend via the "+" above'},
    'friend_add': {'uz': 'Do\'st qo\'shish', 'ru': 'Добавить друга', 'en': 'Add friend'},
    'invite_code_label': {'uz': 'Taklif kodi (6 belgi)', 'ru': 'Код приглашения (6 знаков)', 'en': 'Invite code (6 chars)'},
    'your_invite_code': {'uz': 'Sizning taklif kodingiz', 'ru': 'Ваш код приглашения', 'en': 'Your invite code'},
    'share_invite_help': {'uz': 'Kodni do\'stga yuboring - ular sizni do\'st sifatida qo\'sha oladi', 'ru': 'Отправьте код другу - он добавит вас', 'en': 'Send the code to a friend - they can add you'},
    'wrong_amount': {'uz': 'Noto\'g\'ri miqdor', 'ru': 'Неверная сумма', 'en': 'Wrong amount'},
    'challenge_no_friend': {'uz': 'Avval "Do\'stlar" bo\'limida do\'st qo\'shing', 'ru': 'Сначала добавьте друга', 'en': 'First add a friend in the Friends tab'},
    'challenge_new': {'uz': 'Yangi chellenj', 'ru': 'Новый челлендж', 'en': 'New challenge'},
    'challenge_today_score': {'uz': 'Bugungi ball', 'ru': 'Очки за сегодня', 'en': 'Today\'s score'},
    'challenge_empty': {'uz': 'Chellenj yo\'q', 'ru': 'Челленджей нет', 'en': 'No challenges'},
    'challenge_empty_sub': {'uz': 'Do\'stingiz bilan 7 kunlik turnir yarating', 'ru': 'Создайте 7-дневный турнир с другом', 'en': 'Create a 7-day tournament with a friend'},
    'challenge_friend_7day': {'uz': 'Do\'st bilan 7 kunlik turnir', 'ru': '7-дневный турнир с другом', 'en': '7-day tournament with a friend'},
    'challenge_start': {'uz': 'Chellenj boshlash', 'ru': 'Начать челлендж', 'en': 'Start challenge'},
    'challenge_friend_score': {'uz': 'Do\'st ballini kiritish', 'ru': 'Ввести очки друга', 'en': 'Enter friend\'s score'},
    'flashcards_empty': {'uz': 'Hali flashcards yo\'q', 'ru': 'Карточек пока нет', 'en': 'No flashcards yet'},
    'flashcards_empty_sub': {'uz': 'Yangi deck yarating - yodlash oson bo\'ladi', 'ru': 'Создайте колоду - запоминайте легче', 'en': 'Create a deck - memorise faster'},
    'flashcard_no_repeat': {'uz': 'Takrorlash uchun karta yo\'q', 'ru': 'Нет карточек для повторения', 'en': 'No cards to review'},
    'flashcard_no_card': {'uz': 'Karta yo\'q', 'ru': 'Нет карточек', 'en': 'No cards'},
    'flashcard_tap_for_back': {'uz': 'Javobni ko\'rish uchun kartaga bosing', 'ru': 'Нажмите чтобы увидеть ответ', 'en': 'Tap to see the answer'},
    'deck_new': {'uz': 'Yangi deck', 'ru': 'Новая колода', 'en': 'New deck'},
    'deck_name': {'uz': 'Deck nomi', 'ru': 'Название колоды', 'en': 'Deck name'},
    'card_new': {'uz': 'Yangi karta', 'ru': 'Новая карточка', 'en': 'New card'},
    'card_front_q': {'uz': 'Old tomon (savol)', 'ru': 'Лицевая (вопрос)', 'en': 'Front (question)'},
    'card_back_a': {'uz': 'Orqa tomon (javob)', 'ru': 'Обратная (ответ)', 'en': 'Back (answer)'},
    'card_add_help': {'uz': 'Old-orqa tomon bilan karta qo\'shing', 'ru': 'Добавьте карточку с двумя сторонами', 'en': 'Add a card with both sides'},
    'flashcard_label': {'uz': 'Flashcard deck', 'ru': 'Колода Flashcard', 'en': 'Flashcard deck'},
    'smart_plan_title': {'uz': 'Aqlli reja', 'ru': 'Умный план', 'en': 'Smart plan'},
    'smart_plan_intro': {'uz': 'Soat va yo\'nalishni belgilab, reja yarating. AI shu vaqtni optimal bloklarga bo\'ladi.', 'ru': 'Укажите время и направление - AI распределит на блоки.', 'en': 'Set time and focus - AI splits it into optimal blocks.'},
    'smart_plan_hours_q': {'uz': 'Qancha vaqtingiz bor?', 'ru': 'Сколько у вас времени?', 'en': 'How much time do you have?'},
    'direction_label': {'uz': 'Yo\'nalish:', 'ru': 'Направление:', 'en': 'Direction:'},
    'split_to_blocks': {'uz': 'Vaqtni optimal bloklarga bo\'lish', 'ru': 'Распределить на блоки', 'en': 'Split into optimal blocks'},
    'no_plans_yet': {'uz': 'Hozircha rejalar yo\'q', 'ru': 'Планов пока нет', 'en': 'No plans yet'},
    'pick_we_plan': {'uz': 'Tanlang - biz sizga mos reja tuzamiz', 'ru': 'Выберите - подберём план', 'en': 'Pick - we\'ll match a plan'},
    'subject_coding': {'uz': 'Kod / dasturlash', 'ru': 'Код / программирование', 'en': 'Coding / programming'},
    'subject_language': {'uz': 'Til o\'rganish', 'ru': 'Изучение языка', 'en': 'Language learning'},
    'subject_meditation': {'uz': 'Meditatsiya / dam', 'ru': 'Медитация / отдых', 'en': 'Meditation / rest'},
    'subject_sport': {'uz': 'Sport / mashq', 'ru': 'Спорт / тренировка', 'en': 'Sport / workout'},
    'subject_reading': {'uz': 'O\'qish / mashg\'ulot', 'ru': 'Чтение / занятие', 'en': 'Reading / study'},
    'subject_creative': {'uz': 'Ijodiy ish', 'ru': 'Творчество', 'en': 'Creative work'},
    'wrapped_title': {'uz': 'Haftangiz xulosasi', 'ru': 'Итоги недели', 'en': 'Your week wrapped'},
    'wrapped_subtitle': {'uz': 'Bu haftangiz qanday o\'tgani', 'ru': 'Как прошла неделя', 'en': 'How your week went'},
    'wrapped_tasks_done': {'uz': 'Bajarilgan vazifalar', 'ru': 'Выполненные задачи', 'en': 'Tasks completed'},
    'wrapped_tasks_sub': {'uz': 'Bu hafta sizning natijangiz', 'ru': 'Ваш результат за неделю', 'en': 'Your result this week'},
    'wrapped_xp': {'uz': 'XP to\'pladingiz', 'ru': 'Вы набрали XP', 'en': 'XP earned'},
    'wrapped_xp_sub': {'uz': 'Harakatingizning muqobil qiymati', 'ru': 'Эквивалент ваших усилий', 'en': 'Equivalent of your effort'},
    'wrapped_top_cat': {'uz': 'Eng ko\'p kategoriya', 'ru': 'Самая частая категория', 'en': 'Top category'},
    'wrapped_keep_going': {'uz': 'Davom eting!', 'ru': 'Продолжайте!', 'en': 'Keep going!'},
    'wrapped_next_higher': {'uz': 'Keyingi hafta yana balandroq', 'ru': 'На следующей неделе - выше', 'en': 'Next week - higher still'},
    'wrapped_streak': {'uz': 'Streak saqlang', 'ru': 'Сохраняйте streak', 'en': 'Keep the streak'},
    'activity_heatmap': {'uz': 'Faollik (35 kun)', 'ru': 'Активность (35 дней)', 'en': 'Activity (35 days)'},
    'hour_x_day': {'uz': 'Soat - kun', 'ru': 'Час - день', 'en': 'Hour - day'},
    'top_active_hour': {'uz': 'Eng faol soat', 'ru': 'Самый активный час', 'en': 'Most active hour'},
    'top_active_day': {'uz': 'Eng mahsuldor kun', 'ru': 'Самый продуктивный день', 'en': 'Most productive day'},
    'active_streak': {'uz': 'Ketma-ket faollik', 'ru': 'Серия активности', 'en': 'Active streak'},
    'rituals_empty': {'uz': 'Rituallar yo\'q', 'ru': 'Ритуалов нет', 'en': 'No rituals'},
    'ritual_new': {'uz': 'Yangi ritual', 'ru': 'Новый ритуал', 'en': 'New ritual'},
    'ritual_name': {'uz': 'Ritual nomi', 'ru': 'Название ритуала', 'en': 'Ritual name'},
    'ritual_saved': {'uz': 'Ritual saqlandi', 'ru': 'Ритуал сохранён', 'en': 'Ritual saved'},
    'morning_ritual': {'uz': 'Kun boshi rituali', 'ru': 'Утренний ритуал', 'en': 'Morning ritual'},
    'ritual_repeat_help': {'uz': 'Takroriy mashg\'ulotlar uchun eslatma', 'ru': 'Напоминание для регулярных занятий', 'en': 'Reminder for recurring activities'},
    'ritual_examples': {'uz': '"Har ertalab 20 min ingliz" kabi takroriy ishlar', 'ru': 'Регулярные дела типа "20 мин английского утром"', 'en': 'Recurring like "20 min English every morning"'},
    'notif_no': {'uz': 'Bildirishnomalar yo\'q', 'ru': 'Уведомлений нет', 'en': 'No notifications'},
    'notif_style_pick': {'uz': 'Bildirishnoma uslubini tanlang', 'ru': 'Выберите стиль уведомлений', 'en': 'Pick notification style'},
    'notif_test': {'uz': 'MotivAI test', 'ru': 'MotivAI тест', 'en': 'MotivAI test'},
    'notif_remind_min_before': {'uz': 'Vazifadan qancha vaqt oldin eslatish', 'ru': 'За сколько минут напомнить', 'en': 'How long before to remind'},
    'notif_when': {'uz': 'Eslatma vaqti', 'ru': 'Время напоминания', 'en': 'Reminder time'},
    'search_what': {'uz': 'Nimani qidiryapsiz?', 'ru': 'Что вы ищете?', 'en': 'What are you searching for?'},
    'search_hint': {'uz': 'Vazifa, odat yoki flashcard nomini yozing', 'ru': 'Введите название задачи, привычки или карты', 'en': 'Type a task, habit or card name'},
    'no_task_today': {'uz': 'Bu kunda vazifa yo\'q', 'ru': 'На этот день задач нет', 'en': 'No tasks for this day'},
    'dashboard_intro': {'uz': 'AI tavsiya etgan vazifalar', 'ru': 'Задачи от AI', 'en': 'AI-suggested tasks'},
    'dashboard_pick_help': {'uz': 'Tanlang va ro\'yxatingizga qo\'shing', 'ru': 'Выберите и добавьте в список', 'en': 'Pick and add to your list'},
    'add_to_tasks': {'uz': 'Vazifalarga qo\'shish', 'ru': 'Добавить в задачи', 'en': 'Add to tasks'},
    'tasks_add_first': {'uz': 'Vazifa qo\'shing', 'ru': 'Добавьте задачу', 'en': 'Add a task'},
    'task_completed': {'uz': 'Bu vazifa bajarilgan', 'ru': 'Эта задача выполнена', 'en': 'This task is completed'},
    'task_skipped': {'uz': 'Vazifa o\'tkazib yuborildi', 'ru': 'Задача пропущена', 'en': 'Task skipped'},
    'primary_goal_q': {'uz': 'Asosiy maqsadingiz?', 'ru': 'Ваша главная цель?', 'en': 'Your main goal?'},
    'preferred_field': {'uz': 'Ustuvorlik bergan soha', 'ru': 'Приоритетная сфера', 'en': 'Preferred field'},
    'goal_streak': {'uz': 'Streak orqali o\'z-o\'zingizni rivojlantiring', 'ru': 'Развивайтесь через streak', 'en': 'Grow yourself via streak'},
    'goal_rating': {'uz': 'Reytingda yuqorilang', 'ru': 'Поднимайтесь в рейтинге', 'en': 'Climb the leaderboard'},
    'goal_daily_task': {'uz': 'Kuniga vazifa', 'ru': 'Задача в день', 'en': 'A task a day'},
    'general_task': {'uz': 'Umumiy vazifa', 'ru': 'Общая задача', 'en': 'General task'},
    'ai_minute_ground': {'uz': '1 daqiqa - o\'z kuningizni asoslang', 'ru': '1 минута - заземлите свой день', 'en': '1 minute - ground your day'},
    'tree_30_grow': {'uz': '30 kunlik daraxt o\'sishi', 'ru': '30-дневный рост дерева', 'en': '30-day tree growth'},
    'what_did_you_learn': {'uz': 'Nima o\'rgandingiz? Qanday borish mumkin?', 'ru': 'Что выучили? Куда дальше?', 'en': 'What did you learn? Where next?'},
    'add_reflection': {'uz': 'Izoh qo\'shish (reflection)', 'ru': 'Добавить рефлексию', 'en': 'Add reflection'},
    'session_stop_q': {'uz': 'Sessiyani to\'xtatilsinmi?', 'ru': 'Остановить сессию?', 'en': 'Stop session?'},
    'fewer_choices': {'uz': 'Choice overload kamaytiradi', 'ru': 'Снижает перегруз выбора', 'en': 'Reduces choice overload'},
    'type_something': {'uz': 'Bir narsa yozing', 'ru': 'Напишите что-нибудь', 'en': 'Type something'},
    'hi_im_motivai': {'uz': 'Salom! Men MotivAI', 'ru': 'Привет! Я MotivAI', 'en': 'Hi! I\'m MotivAI'},
    'how_can_i_help': {'uz': 'Sizga qanday yordam bera olaman?', 'ru': 'Чем могу помочь?', 'en': 'How can I help you?'},
    'hours_ago': {'uz': 'Soat va kun statistikasi', 'ru': 'Часы и дни', 'en': 'Hours and days'},
    'login_google_btn': {'uz': 'Google bilan kirish', 'ru': 'Войти через Google', 'en': 'Sign in with Google'},
    'min6_char': {'uz': 'Kamida 6 belgi', 'ru': 'Минимум 6 символов', 'en': 'At least 6 characters'},
    'verify_code': {'uz': 'Tasdiq kodi', 'ru': 'Код подтверждения', 'en': 'Verification code'},
    'code_resend_help': {'uz': 'Kod kelmasa, oynani yopib qaytadan boshlang', 'ru': 'Если код не пришёл - закройте и начните снова', 'en': 'If no code arrived - close and try again'},
    'reset_pass_btn': {'uz': 'Parolni tiklash', 'ru': 'Сброс пароля', 'en': 'Reset password'},
    'new_pass_label': {'uz': 'Yangi parol', 'ru': 'Новый пароль', 'en': 'New password'},
    'voice_unavailable': {'uz': 'Ovozli kirish mavjud emas', 'ru': 'Голосовой ввод недоступен', 'en': 'Voice input unavailable'},
    'sound_soon': {'uz': 'Tez orada chalinadi (infratuzilma tayyor)', 'ru': 'Скоро (инфраструктура готова)', 'en': 'Coming soon (infra ready)'},
    'freeze_keeps_streak': {'uz': 'Freeze: streakni saqlaydi bitta-o\'tkazib yuborilgan kunda', 'ru': 'Freeze: спасает streak за один пропущенный день', 'en': 'Freeze: saves streak on a missed day'},
    'last_30_days': {'uz': 'Oxirgi 30 kun', 'ru': 'Последние 30 дней', 'en': 'Last 30 days'},
    'last_8_weeks': {'uz': 'Oxirgi 8 hafta', 'ru': 'Последние 8 недель', 'en': 'Last 8 weeks'},
    'ko_p': {'uz': 'Ko\'p', 'ru': 'Много', 'en': 'Many'},
    'yo_q': {'uz': 'Yo\'q', 'ru': 'Нет', 'en': 'No'},
    'json_paste_hint': {'uz': 'JSON yopishtiring - odat/kartalarga qo\'shiladi', 'ru': 'Вставьте JSON - добавится к привычкам/картам', 'en': 'Paste JSON - habits/cards will be added'},
    'json_paste_friend': {'uz': 'Do\'stingizdan olgan JSON ni yopishtiring', 'ru': 'Вставьте JSON, полученный от друга', 'en': 'Paste JSON received from a friend'},
    'share_habits_cards': {'uz': 'Odatlar + kartalar - do\'stga yuboring', 'ru': 'Привычки + карты - другу', 'en': 'Habits + cards - send to a friend'},
    'json_sample': {'uz': '{"app":"MotivAI", ...}', 'ru': '{"app":"MotivAI", ...}', 'en': '{"app":"MotivAI", ...}'},
    'tap_test_now': {'uz': 'Tanlang va darhol sinab ko\'ring', 'ru': 'Выберите и тут же попробуйте', 'en': 'Pick and try right away'},
    'task_remind_examples': {'uz': 'Masalan: 3 vazifani tugatish', 'ru': 'Например: завершить 3 задачи', 'en': 'E.g. finish 3 tasks'},
    'tasks_reminders_wins': {'uz': 'Vazifalar, eslatmalar va yutuqlar', 'ru': 'Задачи, напоминания и достижения', 'en': 'Tasks, reminders and wins'},
    'fokus_pomodoro': {'uz': 'Fokus (Pomodoro)', 'ru': 'Фокус (Pomodoro)', 'en': 'Focus (Pomodoro)'},
    'pomodoro_breaks': {'uz': 'Pomodoro tanaffuslar', 'ru': 'Перерывы Pomodoro', 'en': 'Pomodoro breaks'},
    'ambient_sound': {'uz': 'Fon ovozi', 'ru': 'Фоновая музыка', 'en': 'Ambient sound'},
    'tasks_show_here': {'uz': 'Vazifalaringizga vaqt qo\'shing -\neslatmalar shu yerda ko\'rinadi', 'ru': 'Добавьте время к задачам -\nнапоминания будут здесь', 'en': 'Add time to your tasks -\nreminders will appear here'},
    // ── Added by apply_i18n_pass2.py ──
    'delete_btn': {'uz': 'O\'chirish', 'ru': 'Удалить', 'en': 'Delete'},
    'skip_btn': {'uz': 'O\'tkazib yuborish', 'ru': 'Пропустить', 'en': 'Skip'},
    'stop_btn': {'uz': 'To\'xtatish', 'ru': 'Остановить', 'en': 'Stop'},
    'continue_action': {'uz': 'Davom etish', 'ru': 'Продолжить', 'en': 'Continue'},
    'type_something_x': {'uz': 'Bir narsa yozing', 'ru': 'Напишите что-нибудь', 'en': 'Type something'},
    'many': {'uz': 'Ko\'p', 'ru': 'Много', 'en': 'Many'},
    'guide': {'uz': 'Qo\'llanma', 'ru': 'Руководство', 'en': 'Guide'},
    'add_action': {'uz': 'Qo\'shish', 'ru': 'Добавить', 'en': 'Add'},
    'import_temp': {'uz': 'Template import', 'ru': 'Импорт шаблона', 'en': 'Import template'},
    'task_skipped_msg': {'uz': 'Vazifa o\'tkazib yuborildi', 'ru': 'Задача пропущена', 'en': 'Task skipped'},
    'no_card_yet': {'uz': 'Hali karta yo\'q', 'ru': 'Карточек пока нет', 'en': 'No cards yet'},
    'tasks_reminders_wins_msg': {'uz': 'Vazifalar, eslatmalar va yutuqlar', 'ru': 'Задачи, напоминания и достижения', 'en': 'Tasks, reminders and wins'},
    'send_friend_json': {'uz': 'Odatlar + kartalar - do\'stga yuboring', 'ru': 'Привычки + карты - другу', 'en': 'Habits + cards - send to a friend'},
    'deck_yarating': {'uz': 'Yangi deck yarating - yodlash oson bo\'ladi', 'ru': 'Создайте колоду - запоминайте легче', 'en': 'Create a deck - memorise faster'},
    'habits_grow_streak': {'uz': 'Kundalik odat qo\'shing - streak orttiring', 'ru': 'Добавьте привычку - растите streak', 'en': 'Add a daily habit - grow your streak'},
    'auto_dark_light': {'uz': 'Kechqurun dark, kunduzi light - avtomatik', 'ru': 'Вечером - тёмная, днём - светлая', 'en': 'Dark at night, light by day - auto'},
    'json_paste_help': {'uz': 'JSON yopishtiring - odat/kartalarga qo\'shiladi', 'ru': 'Вставьте JSON - добавится к привычкам/картам', 'en': 'Paste JSON - habits/cards will be added'},
    'send_invite': {'uz': 'Kodni do\'stga yuboring - ular sizni do\'st sifatida qo\'sha oladi', 'ru': 'Отправьте код другу - он добавит вас', 'en': 'Send the code to a friend - they can add you'},
    'ai_one_minute': {'uz': '1 daqiqa - o\'z kuningizni asoslang', 'ru': '1 минута - заземлите свой день', 'en': '1 minute - ground your day'},
    'ground_motto': {'uz': 'Maqsadga - har kuni bir qadam', 'ru': 'К цели - каждый день по шагу', 'en': 'One step closer every day'},
    'hour_day': {'uz': 'Soat - kun', 'ru': 'Час - день', 'en': 'Hour - day'},
    'tap_we_plan': {'uz': 'Tanlang - biz sizga mos reja tuzamiz', 'ru': 'Выберите - подберём план', 'en': 'Pick - we\'ll match a plan'},
    'export_data_btn': {'uz': 'Ma\'lumotlarni eksport', 'ru': 'Экспорт данных', 'en': 'Export data'},
    'mark_all_read_btn': {'uz': 'Barchasini o\'qilgan qilish', 'ru': 'Отметить всё прочитанным', 'en': 'Mark all as read'},
    'tasks_show_here_x': {'uz': 'Vazifalaringizga vaqt qo\'shing -\neslatmalar shu yerda ko\'rinadi', 'ru': 'Добавьте время к задачам -\nнапоминания будут здесь', 'en': 'Add time to your tasks -\nreminders will appear here'},
    // ── Added by interp_units.py ──
    'unit_day': {'uz': 'kun', 'ru': 'дн.', 'en': 'days'},
    'unit_hour': {'uz': 'soat', 'ru': 'ч.', 'en': 'hours'},
    'unit_minute': {'uz': 'daqiqa', 'ru': 'мин.', 'en': 'minutes'},
    'unit_coin': {'uz': 'tanga', 'ru': 'монет', 'en': 'coins'},
    'day_streak': {'uz': 'kunlik streak', 'ru': 'дней streak', 'en': 'day streak'},
    'review_count': {'uz': 'ta takror', 'ru': 'повтор.', 'en': 'to review'},
    'results_count': {'uz': 'ta natija', 'ru': 'результ.', 'en': 'results'},
    'remaining': {'uz': 'ta', 'ru': '', 'en': ''},
    'focused_min': {'uz': 'daqiqa fokuslangansiz. ', 'ru': 'минут сосредоточения. ', 'en': 'minutes focused. '},
    // ── Smart reminder ──
    'smart_reminder': {'uz': 'Aqlli eslatma', 'ru': 'Умное напоминание', 'en': 'Smart reminder'},
    'smart_reminder_sub_on': {'uz': 'Bugun {h}:00 da yuboriladi', 'ru': 'Сегодня в {h}:00', 'en': 'Today at {h}:00'},
    'smart_reminder_sub_off': {'uz': 'O\'chirilgan', 'ru': 'Выключено', 'en': 'Off'},
    'smart_reminder_pick_hour': {'uz': 'Eslatma soatini tanlang', 'ru': 'Выберите час', 'en': 'Pick reminder hour'},
    'smart_reminder_auto': {'uz': 'Avtomatik (faollik bo\'yicha)', 'ru': 'Автоматически (по активности)', 'en': 'Automatic (by activity)'},
    // ── Task categories (used by S.get(category)) ──
    'study':        {'uz': 'O\'qish', 'ru': 'Учёба', 'en': 'Study'},
    'exercise':     {'uz': 'Sport', 'ru': 'Спорт', 'en': 'Exercise'},
    'reading':      {'uz': 'Mutolaa', 'ru': 'Чтение', 'en': 'Reading'},
    'meditation':   {'uz': 'Meditatsiya', 'ru': 'Медитация', 'en': 'Meditation'},
    'social':       {'uz': 'Ijtimoiy', 'ru': 'Общение', 'en': 'Social'},
    'creative':     {'uz': 'Ijodiy', 'ru': 'Творчество', 'en': 'Creative'},
    'productivity': {'uz': 'Mahsuldorlik', 'ru': 'Продуктивность', 'en': 'Productivity'},
    'challenge':    {'uz': 'Chellenj', 'ru': 'Челлендж', 'en': 'Challenge'},
    // ── Added by apply_i18n_pass3.py ──
    'did_it': {'uz': 'Bajardim', 'ru': 'Сделал', 'en': 'Did it'},
    'edit_btn': {'uz': 'Tahrirlash', 'ru': 'Редактировать', 'en': 'Edit'},
    'pin_btn': {'uz': 'Pin qilish', 'ru': 'Закрепить', 'en': 'Pin'},
    'unpin_btn': {'uz': 'Pinni yechish', 'ru': 'Открепить', 'en': 'Unpin'},
    'upcoming_label': {'uz': 'Yaqinlashmoqda', 'ru': 'Скоро', 'en': 'Upcoming'},
    'hour_short': {'uz': 'Soat', 'ru': 'Часы', 'en': 'Hour'},
    'minute_short': {'uz': 'Daqiqa', 'ru': 'Минуты', 'en': 'Minute'},
    'days_label': {'uz': 'Kunlar', 'ru': 'Дни', 'en': 'Days'},
    'reminder_prefix': {'uz': 'Eslatma', 'ru': 'Напоминание', 'en': 'Reminder'},
    'title_pin': {'uz': 'Pin', 'ru': 'Закр.', 'en': 'Pin'},
    'edit_task': {'uz': 'Vazifani tahrirlash', 'ru': 'Редактировать задачу', 'en': 'Edit task'},
    'enter_task_name': {'uz': 'Vazifa nomini kiriting', 'ru': 'Введите название задачи', 'en': 'Enter task name'},
    'select_task': {'uz': 'Vazifa tanlang', 'ru': 'Выберите задачу', 'en': 'Select a task'},
    'level_with': {'uz': 'Daraja', 'ru': 'Уровень', 'en': 'Level'},
    // ── Added by apply_i18n_pass4.py ──
    'min_ago': {'uz': 'min oldin', 'ru': 'мин. назад', 'en': 'min ago'},
    'hour_ago': {'uz': 'soat oldin', 'ru': 'ч. назад', 'en': 'hr ago'},
    'day_ago': {'uz': 'kun oldin', 'ru': 'дн. назад', 'en': 'd ago'},
    'min_before': {'uz': 'daqiqa oldin', 'ru': 'мин. до', 'en': 'min before'},
    'min_before_remind': {'uz': 'min oldin eslatma', 'ru': 'мин. напомнить', 'en': 'min before reminder'},
    'min_starts_in': {'uz': 'daqiqadan keyin boshlanadi', 'ru': 'минут до начала', 'en': 'minutes till start'},
    'min_arrives': {'uz': '5 soniyadan keyin yetib keladi', 'ru': 'Придёт через 5 секунд', 'en': 'Arrives in 5s'},
    'after_days': {'uz': 'Keyin {n} kunda', 'ru': 'Через {n} дн.', 'en': 'In {n} days'},
    'after_hours': {'uz': 'Keyin {n} soat', 'ru': 'Через {n} ч.', 'en': 'In {n} hours'},
    'after_minutes': {'uz': 'Keyin {n} daqiqa', 'ru': 'Через {n} мин.', 'en': 'In {n} minutes'},
    'select_at_least': {'uz': 'Kamida bitta vazifa tanlang', 'ru': 'Выберите хотя бы одну задачу', 'en': 'Select at least one task'},
    'plan_created': {'uz': 'Reja yaratildi - Bosh sahifadan ko\'ring', 'ru': 'План создан - смотрите на главной', 'en': 'Plan created - see on Home'},
    'task_done_caps': {'uz': 'VAZIFA BAJARILDI!', 'ru': 'ЗАДАЧА ВЫПОЛНЕНА!', 'en': 'TASK COMPLETED!'},
    'no_done_yet': {'uz': 'Hali bajarilgan vazifa yo\'q', 'ru': 'Выполненных задач пока нет', 'en': 'No completed tasks yet'},
    'mit_3': {'uz': 'MIT rejim: eng muhim 3 vazifa', 'ru': 'MIT режим: 3 важнейшие задачи', 'en': 'MIT mode: 3 most important'},
    'no_plan_for_task': {'uz': 'Ushbu vazifa uchun plan topilmadi', 'ru': 'План для задачи не найден', 'en': 'No plan found for this task'},
    'fake_email': {'uz': 'Bu email vaqtinchalik/soxta. Real email kiriting.', 'ru': 'Этот email временный. Введите настоящий.', 'en': 'This is a temporary email. Enter a real one.'},
    'account_locked': {'uz': 'Hisob bloklangan', 'ru': 'Аккаунт заблокирован', 'en': 'Account locked'},
    'cancel_caps': {'uz': 'BEKOR QILISH', 'ru': 'ОТМЕНА', 'en': 'CANCEL'},
    'every_leaf': {'uz': 'Har bargda - siz qilgan bir vazifa.', 'ru': 'Каждый лист - выполненная задача.', 'en': 'Each leaf is a completed task.'},
    'tree_flower': {'uz': 'Yana {n} kun ish qilib daraxtni gullattring.', 'ru': 'Ещё {n} дней - и дерево зацветёт.', 'en': '{n} more days to make the tree bloom.'},
    'ai_step_motto': {'uz': 'Maqsadga har kuni bir qadam - AI bilan motivatsion reja.', 'ru': 'К цели по шагу - план с AI-мотивацией.', 'en': 'One step a day - AI-driven motivation plan.'},
    'smart_plan_subj': {'uz': 'Aqlli reja', 'ru': 'Умный план', 'en': 'Smart plan'},
    'tasks_added_n': {'uz': '{n} ta vazifa qo\'shildi!', 'ru': 'Добавлено {n} задач!', 'en': '{n} tasks added!'},
    'imported_x': {'uz': 'Import qo\'shildi: {a} odat, {b} kolod, {c} karta', 'ru': 'Импорт: {a} привычек, {b} колод, {c} карт', 'en': 'Imported: {a} habits, {b} decks, {c} cards'},
    'today_goal_short': {'uz': 'Bugungi maqsad', 'ru': 'Цель дня', 'en': 'Today\'s goal'},
    'morning_minute': {'uz': '1 daqiqa - kayfiyat, maqsad, minnatdorlik', 'ru': '1 минута - настроение, цель, благодарность', 'en': '1 minute - mood, goal, gratitude'},
    'enter_otp': {'uz': 'Tasdiq kodini kiriting', 'ru': 'Введите код подтверждения', 'en': 'Enter verification code'},
    'new_achievements': {'uz': 'Yangi yutuqlar: {n}', 'ru': 'Новые достижения: {n}', 'en': 'New achievements: {n}'},
    'friend_score_q': {'uz': '{name} ning bugun bajargan vazifalari sonini kiriting', 'ru': 'Введите количество задач друга {name}', 'en': 'Enter task count for {name}'},
    'challenge_recap': {'uz': '{a} vazifa/kun × {b} kun', 'ru': '{a} задач/день × {b} дн.', 'en': '{a} tasks/day × {b} days'},
  };
}
